/**
 * Lista de especies arbóreas comunes en el Valle del Cauca, Colombia.
 * Cada entrada incluye nombre científico y nombre común.
 */

export interface EspecieArbol {
  nombre_cientifico: string;
  nombre_comun: string;
}

export const ESPECIES_ARBOLES: EspecieArbol[] = [
  // ── Nativas ──────────────────────────────────────────
  { nombre_cientifico: "Anacardium excelsum", nombre_comun: "Caracolí" },
  { nombre_cientifico: "Annona muricata", nombre_comun: "Guanábana" },
  { nombre_cientifico: "Artocarpus altilis", nombre_comun: "Árbol del pan" },
  { nombre_cientifico: "Astronium graveolens", nombre_comun: "Diomate" },
  { nombre_cientifico: "Bambusa vulgaris", nombre_comun: "Bambú" },
  { nombre_cientifico: "Brosimum alicastrum", nombre_comun: "Guáimaro" },
  { nombre_cientifico: "Brownea ariza", nombre_comun: "Palo de cruz" },
  { nombre_cientifico: "Bursera simaruba", nombre_comun: "Indio desnudo" },
  { nombre_cientifico: "Byrsonima crassifolia", nombre_comun: "Noro" },
  { nombre_cientifico: "Caesalpinia ebano", nombre_comun: "Ébano" },
  { nombre_cientifico: "Calliandra pittieri", nombre_comun: "Carbonero rojo" },
  { nombre_cientifico: "Calophyllum brasiliense", nombre_comun: "Aceite maría" },
  { nombre_cientifico: "Cassia grandis", nombre_comun: "Cañafístula" },
  { nombre_cientifico: "Cedrela odorata", nombre_comun: "Cedro" },
  { nombre_cientifico: "Ceiba pentandra", nombre_comun: "Ceiba" },
  { nombre_cientifico: "Chrysophyllum cainito", nombre_comun: "Caimito" },
  { nombre_cientifico: "Citharexylum kunthianum", nombre_comun: "Cajeto" },
  { nombre_cientifico: "Clusia multiflora", nombre_comun: "Gaque" },
  { nombre_cientifico: "Clusia rosea", nombre_comun: "Clusia" },
  { nombre_cientifico: "Coccoloba uvifera", nombre_comun: "Uvito de playa" },
  { nombre_cientifico: "Cordia alliodora", nombre_comun: "Nogal cafetero" },
  { nombre_cientifico: "Cordia gerascanthus", nombre_comun: "Solera" },
  { nombre_cientifico: "Cordia sebestena", nombre_comun: "Uvito" },
  { nombre_cientifico: "Crescentia cujete", nombre_comun: "Totumo" },
  { nombre_cientifico: "Croton funckianus", nombre_comun: "Sangregado" },
  { nombre_cientifico: "Cupania americana", nombre_comun: "Mestizo" },
  { nombre_cientifico: "Dalbergia retusa", nombre_comun: "Cocobolo" },
  { nombre_cientifico: "Enterolobium cyclocarpum", nombre_comun: "Piñón de oreja" },
  { nombre_cientifico: "Erythrina fusca", nombre_comun: "Cachimbo" },
  { nombre_cientifico: "Erythrina poeppigiana", nombre_comun: "Cámbulo" },
  { nombre_cientifico: "Eugenia malaccensis", nombre_comun: "Marañón japonés" },
  { nombre_cientifico: "Ficus benjamina", nombre_comun: "Caucho benjamín" },
  { nombre_cientifico: "Ficus elastica", nombre_comun: "Caucho" },
  { nombre_cientifico: "Ficus insipida", nombre_comun: "Higuerón" },
  { nombre_cientifico: "Ficus lyrata", nombre_comun: "Caucho lira" },
  { nombre_cientifico: "Genipa americana", nombre_comun: "Jagua" },
  { nombre_cientifico: "Gliricidia sepium", nombre_comun: "Matarratón" },
  { nombre_cientifico: "Guadua angustifolia", nombre_comun: "Guadua" },
  { nombre_cientifico: "Guarea guidonia", nombre_comun: "Trompillo" },
  { nombre_cientifico: "Guazuma ulmifolia", nombre_comun: "Guácimo" },
  { nombre_cientifico: "Gustavia superba", nombre_comun: "Membrillo" },
  { nombre_cientifico: "Handroanthus chrysanthus", nombre_comun: "Guayacán amarillo" },
  { nombre_cientifico: "Handroanthus rosea", nombre_comun: "Guayacán rosado" },
  { nombre_cientifico: "Hura crepitans", nombre_comun: "Ceiba bruja" },
  { nombre_cientifico: "Hymenaea courbaril", nombre_comun: "Algarrobo" },
  { nombre_cientifico: "Inga edulis", nombre_comun: "Guamo" },
  { nombre_cientifico: "Inga spectabilis", nombre_comun: "Guamo machete" },
  { nombre_cientifico: "Jacaranda caucana", nombre_comun: "Gualanday" },
  { nombre_cientifico: "Juglans neotropica", nombre_comun: "Nogal" },
  { nombre_cientifico: "Lafoensia speciosa", nombre_comun: "Guayacán de Manizales" },
  { nombre_cientifico: "Luehea seemannii", nombre_comun: "Guácimo colorado" },
  { nombre_cientifico: "Machaerium capote", nombre_comun: "Capote" },
  { nombre_cientifico: "Mammea americana", nombre_comun: "Mamey" },
  { nombre_cientifico: "Mangifera indica", nombre_comun: "Mango" },
  { nombre_cientifico: "Matisia cordata", nombre_comun: "Zapote" },
  { nombre_cientifico: "Melicoccus bijugatus", nombre_comun: "Mamoncillo" },
  { nombre_cientifico: "Myrcia popayanensis", nombre_comun: "Arrayán" },
  { nombre_cientifico: "Myroxylon balsamum", nombre_comun: "Bálsamo" },
  { nombre_cientifico: "Nectandra reticulata", nombre_comun: "Laurel" },
  { nombre_cientifico: "Ochroma pyramidale", nombre_comun: "Balso" },
  { nombre_cientifico: "Ocotea aurantiodora", nombre_comun: "Laurel amarillo" },
  { nombre_cientifico: "Persea americana", nombre_comun: "Aguacate" },
  { nombre_cientifico: "Pithecellobium dulce", nombre_comun: "Chiminango" },
  { nombre_cientifico: "Pithecellobium lanceolatum", nombre_comun: "Espino de mono" },
  { nombre_cientifico: "Platymiscium pinnatum", nombre_comun: "Otobo" },
  { nombre_cientifico: "Podocarpus oleifolius", nombre_comun: "Pino colombiano" },
  { nombre_cientifico: "Prosopis juliflora", nombre_comun: "Trupillo" },
  { nombre_cientifico: "Pseudobombax septenatum", nombre_comun: "Ceiba verde" },
  { nombre_cientifico: "Pseudosamanea guachapele", nombre_comun: "Igua" },
  { nombre_cientifico: "Psidium guajava", nombre_comun: "Guayaba" },
  { nombre_cientifico: "Pterocarpus acapulcensis", nombre_comun: "Sángre de drago" },
  { nombre_cientifico: "Quercus humboldtii", nombre_comun: "Roble" },
  { nombre_cientifico: "Samanea saman", nombre_comun: "Samán" },
  { nombre_cientifico: "Sapindus saponaria", nombre_comun: "Jaboncillo" },
  { nombre_cientifico: "Schizolobium parahyba", nombre_comun: "Tambor" },
  { nombre_cientifico: "Spathodea campanulata", nombre_comun: "Tulipán africano" },
  { nombre_cientifico: "Spondias mombin", nombre_comun: "Hobo" },
  { nombre_cientifico: "Spondias purpurea", nombre_comun: "Ciruelo" },
  { nombre_cientifico: "Sterculia apetala", nombre_comun: "Camajón" },
  { nombre_cientifico: "Swietenia macrophylla", nombre_comun: "Caoba" },
  { nombre_cientifico: "Syzygium malaccense", nombre_comun: "Pero de agua" },
  { nombre_cientifico: "Tabebuia rosea", nombre_comun: "Ocobo" },
  { nombre_cientifico: "Tamarindus indica", nombre_comun: "Tamarindo" },
  { nombre_cientifico: "Tecoma stans", nombre_comun: "Chicalá" },
  { nombre_cientifico: "Terminalia catappa", nombre_comun: "Almendro" },
  { nombre_cientifico: "Triplaris americana", nombre_comun: "Varasanta" },
  { nombre_cientifico: "Vitex cymosa", nombre_comun: "Aceituno" },
  { nombre_cientifico: "Zanthoxylum rhoifolium", nombre_comun: "Tachuelo" },

  // ── Ornamentales / Introducidas de uso urbano ────────
  { nombre_cientifico: "Acacia mangium", nombre_comun: "Acacia" },
  { nombre_cientifico: "Araucaria heterophylla", nombre_comun: "Araucaria" },
  { nombre_cientifico: "Bauhinia variegata", nombre_comun: "Casco de vaca" },
  { nombre_cientifico: "Callistemon citrinus", nombre_comun: "Calistemo" },
  { nombre_cientifico: "Cananga odorata", nombre_comun: "Cadmio" },
  { nombre_cientifico: "Cassia fistula", nombre_comun: "Lluvia de oro" },
  { nombre_cientifico: "Casuarina equisetifolia", nombre_comun: "Casuarina" },
  { nombre_cientifico: "Cinnamomum zeylanicum", nombre_comun: "Canelo" },
  { nombre_cientifico: "Citrus sinensis", nombre_comun: "Naranjo" },
  { nombre_cientifico: "Delonix regia", nombre_comun: "Flamboyán" },
  { nombre_cientifico: "Eucalyptus globulus", nombre_comun: "Eucalipto" },
  { nombre_cientifico: "Eugenia uniflora", nombre_comun: "Cerezo" },
  { nombre_cientifico: "Fraxinus chinensis", nombre_comun: "Urapán" },
  { nombre_cientifico: "Grevillea robusta", nombre_comun: "Roble australiano" },
  { nombre_cientifico: "Jacaranda mimosifolia", nombre_comun: "Jacarandá" },
  { nombre_cientifico: "Lagerstroemia speciosa", nombre_comun: "Reina de las flores" },
  { nombre_cientifico: "Leucaena leucocephala", nombre_comun: "Leucaena" },
  { nombre_cientifico: "Melia azedarach", nombre_comun: "Paraíso" },
  { nombre_cientifico: "Phoenix roebelenii", nombre_comun: "Palma robelina" },
  { nombre_cientifico: "Platanus orientalis", nombre_comun: "Plátano de sombra" },
  { nombre_cientifico: "Roystonea regia", nombre_comun: "Palma real" },
  { nombre_cientifico: "Swinglea glutinosa", nombre_comun: "Swinglea" },
  { nombre_cientifico: "Syagrus romanzoffiana", nombre_comun: "Palma reina" },
  { nombre_cientifico: "Tipuana tipu", nombre_comun: "Tipuana" },
  { nombre_cientifico: "Washingtonia robusta", nombre_comun: "Palma washingtonia" },

  // ── Frutales comunes en arbolado urbano ──────────────
  { nombre_cientifico: "Annona cherimola", nombre_comun: "Chirimoya" },
  { nombre_cientifico: "Artocarpus heterophyllus", nombre_comun: "Jackfruit" },
  { nombre_cientifico: "Averrhoa carambola", nombre_comun: "Carambolo" },
  { nombre_cientifico: "Bactris gasipaes", nombre_comun: "Chontaduro" },
  { nombre_cientifico: "Borojoa patinoi", nombre_comun: "Borojó" },
  { nombre_cientifico: "Carica papaya", nombre_comun: "Papaya" },
  { nombre_cientifico: "Cocos nucifera", nombre_comun: "Palma de coco" },
  { nombre_cientifico: "Inga densiflora", nombre_comun: "Guamo santafereño" },
  { nombre_cientifico: "Manilkara zapota", nombre_comun: "Níspero" },
  { nombre_cientifico: "Pouteria sapota", nombre_comun: "Zapote mamey" },
  { nombre_cientifico: "Theobroma cacao", nombre_comun: "Cacao" },

  // ── Otras de importancia regional ────────────────────
  { nombre_cientifico: "Albizia carbonaria", nombre_comun: "Carbonero" },
  { nombre_cientifico: "Cecropia peltata", nombre_comun: "Yarumo" },
  { nombre_cientifico: "Chloroleucon mangense", nombre_comun: "Igua negro" },
  { nombre_cientifico: "Cupressus lusitanica", nombre_comun: "Ciprés" },
  { nombre_cientifico: "Eriobotrya japonica", nombre_comun: "Níspero japonés" },
  { nombre_cientifico: "Ficus microcarpa", nombre_comun: "Laurel de la India" },
  { nombre_cientifico: "Gynerium sagittatum", nombre_comun: "Caña brava" },
  { nombre_cientifico: "Inga oerstediana", nombre_comun: "Guamo de río" },
  { nombre_cientifico: "Miconia caudata", nombre_comun: "Niguito" },
  { nombre_cientifico: "Morinda citrifolia", nombre_comun: "Noni" },
  { nombre_cientifico: "Muntingia calabura", nombre_comun: "Chicle" },
  { nombre_cientifico: "Pinus patula", nombre_comun: "Pino" },
  { nombre_cientifico: "Schefflera actinophylla", nombre_comun: "Cheflera" },
  { nombre_cientifico: "Senna spectabilis", nombre_comun: "Vainillo" },
  { nombre_cientifico: "Trichanthera gigantea", nombre_comun: "Nacedero" },
  { nombre_cientifico: "Urera baccifera", nombre_comun: "Ortiga" },
  { nombre_cientifico: "Xylopia aromatica", nombre_comun: "Malagueto" },
].sort((a, b) => a.nombre_comun.localeCompare(b.nombre_comun, "es"));
