// Datos estáticos de especies. Ampliar o reemplazar con endpoint real si se requiere.
export interface EspecieArbol {
  nombre_comun: string;
  nombre_cientifico: string;
}

export const ESPECIES_ARBOLES: EspecieArbol[] = [
  // Nativas Valle del Cauca / Eje Cafetero
  { nombre_comun: "Acacia amarilla",       nombre_cientifico: "Senna spectabilis" },
  { nombre_comun: "Acacia japonesa",        nombre_cientifico: "Acacia melanoxylon" },
  { nombre_comun: "Acacia negra",           nombre_cientifico: "Acacia decurrens" },
  { nombre_comun: "Aguacate",               nombre_cientifico: "Persea americana" },
  { nombre_comun: "Ahumado",                nombre_cientifico: "Minquartia guianensis" },
  { nombre_comun: "Algarrobo",              nombre_cientifico: "Hymenaea courbaril" },
  { nombre_comun: "Almendro",               nombre_cientifico: "Terminalia catappa" },
  { nombre_comun: "Aromo",                  nombre_cientifico: "Vachellia farnesiana" },
  { nombre_comun: "Balso",                  nombre_cientifico: "Ochroma pyramidale" },
  { nombre_comun: "Bayomero",               nombre_cientifico: "Casearia corymbosa" },
  { nombre_comun: "Botón de oro",           nombre_cientifico: "Tithonia diversifolia" },
  { nombre_comun: "Cacao",                  nombre_cientifico: "Theobroma cacao" },
  { nombre_comun: "Caracolí",               nombre_cientifico: "Anacardium excelsum" },
  { nombre_comun: "Carbonero rojo",         nombre_cientifico: "Calliandra haematocephala" },
  { nombre_comun: "Caucho sabanero",        nombre_cientifico: "Ficus soatensis" },
  { nombre_comun: "Caucho tequendama",      nombre_cientifico: "Ficus tequendamae" },
  { nombre_comun: "Cedrela",                nombre_cientifico: "Cedrela odorata" },
  { nombre_comun: "Cedro de altura",        nombre_cientifico: "Cedrela montana" },
  { nombre_comun: "Ceibo",                  nombre_cientifico: "Ceiba pentandra" },
  { nombre_comun: "Ceiba barrigona",        nombre_cientifico: "Cavanillesia platanifolia" },
  { nombre_comun: "Chambimbe",              nombre_cientifico: "Sapindus saponaria" },
  { nombre_comun: "Chagualo",               nombre_cientifico: "Clusia multiflora" },
  { nombre_comun: "Chiminango",             nombre_cientifico: "Pithecellobium dulce" },
  { nombre_comun: "Chingalé",               nombre_cientifico: "Jacaranda caucana" },
  { nombre_comun: "Chontaduro",             nombre_cientifico: "Bactris gasipaes" },
  { nombre_comun: "Cítrico (naranja/limón)", nombre_cientifico: "Citrus spp." },
  { nombre_comun: "Cují",                   nombre_cientifico: "Prosopis juliflora" },
  { nombre_comun: "Dinde (mora de castilla)", nombre_cientifico: "Maclura tinctoria" },
  { nombre_comun: "Drago",                  nombre_cientifico: "Croton magdalenensis" },
  { nombre_comun: "Eucalipto",              nombre_cientifico: "Eucalyptus globulus" },
  { nombre_comun: "Eucalipto pomarroso",    nombre_cientifico: "Eucalyptus camaldulensis" },
  { nombre_comun: "Flor amarillo",          nombre_cientifico: "Handroanthus chrysanthus" },
  { nombre_comun: "Flor morado",            nombre_cientifico: "Handroanthus impetiginosus" },
  { nombre_comun: "Garrocho",               nombre_cientifico: "Viburnum triphyllum" },
  { nombre_comun: "Guácimo",                nombre_cientifico: "Guazuma ulmifolia" },
  { nombre_comun: "Guadua",                 nombre_cientifico: "Guadua angustifolia" },
  { nombre_comun: "Guamo macheto",          nombre_cientifico: "Inga spectabilis" },
  { nombre_comun: "Guamo rabo de mico",     nombre_cientifico: "Inga edulis" },
  { nombre_comun: "Guamo santafereño",      nombre_cientifico: "Inga punctata" },
  { nombre_comun: "Guanábano",              nombre_cientifico: "Annona muricata" },
  { nombre_comun: "Guapuruvu",              nombre_cientifico: "Schizolobium parahyba" },
  { nombre_comun: "Guayabo",                nombre_cientifico: "Psidium guajava" },
  { nombre_comun: "Guayacán amarillo",      nombre_cientifico: "Handroanthus chrysanthus" },
  { nombre_comun: "Guayacán de Manizales",  nombre_cientifico: "Lafoensia speciosa" },
  { nombre_comun: "Guayacán rosado",        nombre_cientifico: "Handroanthus roseus" },
  { nombre_comun: "Helecho arborescente",   nombre_cientifico: "Cyathea caracasana" },
  { nombre_comun: "Higuerón",               nombre_cientifico: "Ficus insipida" },
  { nombre_comun: "Hobo",                   nombre_cientifico: "Spondias mombin" },
  { nombre_comun: "Igua",                   nombre_cientifico: "Pseudosamanea guachapele" },
  { nombre_comun: "Jigua negro",            nombre_cientifico: "Ocotea calophylla" },
  { nombre_comun: "Laurel de cera",         nombre_cientifico: "Morella pubescens" },
  { nombre_comun: "Leucaena",               nombre_cientifico: "Leucaena leucocephala" },
  { nombre_comun: "Lulo",                   nombre_cientifico: "Solanum quitoense" },
  { nombre_comun: "Mango",                  nombre_cientifico: "Mangifera indica" },
  { nombre_comun: "Mano de oso",            nombre_cientifico: "Oreopanax floribundus" },
  { nombre_comun: "Matarratón",             nombre_cientifico: "Gliricidia sepium" },
  { nombre_comun: "Mestizo",                nombre_cientifico: "Cupania americana" },
  { nombre_comun: "Morera",                 nombre_cientifico: "Morus alba" },
  { nombre_comun: "Nacedero",               nombre_cientifico: "Trichanthera gigantea" },
  { nombre_comun: "Neem",                   nombre_cientifico: "Azadirachta indica" },
  { nombre_comun: "Nogal cafetero",         nombre_cientifico: "Cordia alliodora" },
  { nombre_comun: "Palma de cera",          nombre_cientifico: "Ceroxylon quindiuense" },
  { nombre_comun: "Palma real",             nombre_cientifico: "Roystonea regia" },
  { nombre_comun: "Papayuelo",              nombre_cientifico: "Vasconcellea pubescens" },
  { nombre_comun: "Pategallina",            nombre_cientifico: "Myrsine guianensis" },
  { nombre_comun: "Pavito",                 nombre_cientifico: "Jacaranda mimosifolia" },
  { nombre_comun: "Pino romerón",           nombre_cientifico: "Retrophyllum rospigliosii" },
  { nombre_comun: "Pisamo",                 nombre_cientifico: "Erythrina fusca" },
  { nombre_comun: "Pizamo de tierra fría",  nombre_cientifico: "Erythrina edulis" },
  { nombre_comun: "Platanillo",             nombre_cientifico: "Heliconia psittacorum" },
  { nombre_comun: "Saman",                  nombre_cientifico: "Samanea saman" },
  { nombre_comun: "Sangregado",             nombre_cientifico: "Pterocarpus officinalis" },
  { nombre_comun: "Siete cueros",           nombre_cientifico: "Tibouchina lepidota" },
  { nombre_comun: "Tachuelo",               nombre_cientifico: "Fagara rhoifolia" },
  { nombre_comun: "Tambor",                 nombre_cientifico: "Schizolobium parahyba" },
  { nombre_comun: "Totumo",                 nombre_cientifico: "Crescentia cujete" },
  { nombre_comun: "Trébol",                 nombre_cientifico: "Platymiscium pinnatum" },
  { nombre_comun: "Triplaris",              nombre_cientifico: "Triplaris americana" },
  { nombre_comun: "Urapán",                 nombre_cientifico: "Fraxinus chinensis" },
  { nombre_comun: "Yarumo",                 nombre_cientifico: "Cecropia peltata" },
  { nombre_comun: "Yarumo blanco",          nombre_cientifico: "Cecropia telenitida" },
  { nombre_comun: "Zapote",                 nombre_cientifico: "Quararibea cordata" },
].sort((a, b) => a.nombre_comun.localeCompare(b.nombre_comun, "es"));
