export const GRUPOS_DAGMA = [
  "Dirección",
  "Ecosistemas Y UMATA",
  "Calidad Ambiental",
  "Comunicaciones",
  "UMATA",
  "PSA",
  "Cambio Climático",
  "Vivero",
  "Ecourbanismo",
  "Gobernanza",
  "Huertas Urbanas",
  "Flora Urbana",
  "Gerencia Social",
  "Ecosistemas",
  "Acústica",
  "Hídrico",
  "Urbanismo",
  "Residuos Sólidos",
  "Calidad del Aire",
  "Flora",
  "Fauna Silvestre",
  "Trámite",
  "Cuadrilla",
] as const;
